trigger:
  - main

pool:
  name: Hitesh_PC_Office_Pool

steps:
  
  - task: TerraformInstaller@1
    displayName: 'terraforminstall'
    inputs:
      terraformVersion: 'latest'


  - task: TerraformTask@5
    displayName: 'terraform init'
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)\parent_module'
      backendServiceArm: 'Hitesh_Workload_Federation'
      backendAzureRmStorageAccountName: 'hiteshstginit'
      backendAzureRmContainerName: 'hiteshinitcontainer'
      backendAzureRmKey: 'terraform.tfstate'

  - task: TerraformTask@5
    displayName: 'terraform plan'
    inputs:
      provider: 'azurerm'
      command: 'plan'
      workingDirectory: '$(System.DefaultWorkingDirectory)\parent_module'
      environmentServiceNameAzureRM: 'Hitesh_Workload_Federation'


  - task: TerraformTask@5
    displayName: 'terraform apply'
    inputs:
      provider: 'azurerm'
      command: 'apply'
      workingDirectory: '$(System.DefaultWorkingDirectory)\parent_module'
      environmentServiceNameAzureRM: 'Hitesh_Workload_Federation'
