trigger:
  - main

pool:
  name: Hitesh_Laptop_Pool

steps:

- task: TerraformInstaller@1
  displayName: 'Terraform Install'
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  displayName: 'terraform INIT'
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)\parent_module'
    backendServiceArm: 'Hitesh_Workload_Federation'
    backendAzureRmStorageAccountName: 'hiteshstginit'
    backendAzureRmContainerName: 'hiteshinitcontainer'
    backendAzureRmKey: 'terraform.tfstate'

- task: TerraformTask@5
  displayName: 'Terraform Plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)\parent_module'
    environmentServiceNameAzureRM: 'Hitesh_Workload_Federation'


- task: TerraformTask@5
  displayName: 'Terraform Apply'
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)\parent_module'
    commandOptions: '--auto-approve'
    environmentServiceNameAzureRM: 'Hitesh_Workload_Federation'